import atexit
from Code.local_ollama_management import start_ollama, is_ollama_running, terminate_ollama_processes
from Code.functions import query_collection
from Code.config import RUN_LOCALLY

# --- Script --- #

if __name__ == "__main__":
    if RUN_LOCALLY:
        atexit.register(terminate_ollama_processes)
        if not is_ollama_running():
            start_ollama()

    questions = [
        "How many actors are there in the database?", # 0
        "What is the name of the actor with ID 1?", # 1
        "List all movies released in 2006.", # 2
        "Who directed the movie 'The Godfather'?", # 3
        "What is the average rental rate for movies?", # 4
        "How many customers are there in the database?", #5
        "List all movies with a rating higher than 4.5.", #6
        "What is the total revenue generated by all movies?", #7
        "Who are the top 5 actors with the most movies?", #8
        "List all movies released after 2010.", #9
        "What are the top 3 actors from the top 3 most rented movie categories?" #10
    ]
    
    result = query_collection(questions[2])
    if result:
        print("Query Results:")
        for i in range(len(result["ids"])):
            print(f"\nID: {result['ids'][i]}, Distance: {result['distances'][i]}, \nDocument: {result['documents'][i]}\n")
    else:
        print("No results found in the vector collection.")


